Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Login = Saioa hasi
MainGUI.Register= Erregistratu
MainGUI.mainTitle=Ez duzu saioa hasi

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.Erosi=Erosi
ShowSaleGUI.CantBuyOwnProduct =Ez duzu saioa hasi 


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

MainGUIErregistratuta.ErositakoProduktuakIkusi = Erositako produktuak ikusi

LoginGUI.Email=Posta elektronikoa
LoginGUI.Password=Pasahitza
LoginGUI.Login=Saioa hasi
LoginGUI.ErrorQueary=Posta elektronikoa edo pasahitza okerra da
LoginGUI.Error = Saioa hastean errorea

RegisterGUI.Email= Posta elektronikoa
RegisterGUI.Password= Pasahitza
RegisterGUI.ConfirmPassword=	Pasahitza errepikatu
RegisterGUI.Register=Erregistratu
RegisterGUI.Name=Izena
RegisterGUI.Telephone=	Telefonoa
RegisterGUI.Exit =Irten
RegisterGUI.ErrorPassword=Pasahitzak ez dira berdinak
RegisterGUI.ErrorQueary=Eremu guztiak bete behar dira
RegisterGUI.ErrorEmail=Email hori dagoeneko erregistratuta dago
RegisterGUI.Ondo = Erregistroa ondo burutu da
RegisterGUI.CancelButton=Itxi

BuyProductGUI.kontu = Kontu zenbakia


